/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (MediEvil)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x801B5CD0u
#define func_801B5CD0 BootEntry  /* alias */
